### ISSUE TITLE
Files not accessible - returns 404

### ISSUE THREAD

**Issue by simontaen** [jakubroztocil/podcats#20]
When I add the `http://192.168.1.20:5000` to the iPhone's default Podcast player, it detects it and the list of episodes are shown correctly.

However, when I download an episode ,it returns 404

```
192.168.1.32 - - [05/May/2017 20:48:59] "GET / HTTP/1.1" 200 -
192.168.1.32 - - [05/May/2017 20:49:08] "GET /static/Episode_01.mp3 HTTP/1.1" 404 -
```

I'm serving as

```
podcats --host 192.168.1.20 serve Folder_with_episdoes/
```
The `Folder_with_episodes/` contains `Episode_01.mp3` directly and does not have a `static` subfolder.

I'm using python 2.7.11

_Originally posted by @sundarv85 in https://github.com/jakubroztocil/podcats/issues/8#issuecomment-299584307_

**Comment by simontaen** [comment]
I'm having the same issues as outlined above. Serving files with

```
podcats --host 192.168.0.104 serve episode_folder
```

But the files are not accessible, even when trying the most straight forward way through the browser ```http://192.168.0.104:5000/web```

```
192.168.0.151 - - [04/Jan/2019 10:08:50] "GET /web HTTP/1.1" 200 -
192.168.0.151 - - [04/Jan/2019 10:08:52] "GET /static/filename.aac HTTP/1.1" 404 -
```

What am I missing?

**Comment by jakubroztocil** [comment]
@simontaen thanks for the report. This bug only occurred with relative paths — fixed now.
